---
title: "Integrales MC"
output: html_document
---

La siguiente función calcula integrales de funciones reales, "suaves" y de rango Real positivo utilizando el método del rechazo.

```{r}
MonteCarloInt <- function(func,lim1,lim2){
  g <- curve(func, lim1, lim2, n = 10000)
  r <- seq(length=10000, from=lim1, to=lim2)
  f <- func(r)
  max_y = max(f)
  min_y= min(f)
  rand_x <- runif(10000, 0, 1) * (lim2-lim1) + lim1
  rand_y <- runif(10000, 0, 1) * (max_y-min_y) + min_y
  plot(rand_x, rand_y)
  delta <- func(rand_x) - rand_y
  i = 0
  below <- (NULL)
  for(n in delta){i = i+1
                  if(n>0.0){below <- c(below,i)}}
  plot(rand_x[below], rand_y[below])
  interval_integral = (max_y-min_y) * (lim2 - lim1)
  integral  = interval_integral * (length(below)/(1.0*length(rand_y)))
  integral
}  
```

Ahora queremos calcular la integral de $h(x) = [cos(50x)+sin(20x)]^2$ entre $[0,1]$, usando la función implentada anteriormente.

```{r, echo=FALSE}
h <- function(x) (cos(50*x)+sin(20*x))^2
```

```{r}
MonteCarloInt(h,0.0,1.0)
```

Probemos con otra función.
$$p(x) = \frac{1}{\pi(1+x^2)}$$
```{r, echo=FALSE}
p <- function(x) (1/(pi*(1+x^2)))
```

```{r}
MonteCarloInt(p,2.0,30.0)
```

